spring:
  security:
     outh2:
       client:
         registration:
           shop-users-client:
             provider: spring
             client-id: users-client
             client-secret: 123456
             authorization-grant-type: authorization_code
             redirect-uri: "http://127.0.0.1:8005/authorized"
             scope: read
             client-name: shop-users-client
         provider:
           spring:
             issuer-uri: http://127.0.0.1:9100
             